---
title: "Trade-offs and Co-benefits of Landscape Change Scenarios on Bird Communities and Ecosystem Services in the Sacramento-San Joaquin River Delta"
output: html_document
---

## *Delta Water Quality and Ecosystem Restoration Program Grant Agreement Number – Q1996022*

### Work currently in progress (updated September 2021)

We are currently refining several spatially-explicit scenarios of future landscape change in the Delta. These are purely speculative scenarios chosen to represent distinct major drivers of landscape change, allowing us to estimate the direction and magnitude of the effects each scenario would have on multiple metrics of interest in the Delta. Aside from the planned restoration projects incorporated into the restoration scenario, these scenarios do not represent actual plans or recommendations, and while they are meant to represent reasonably plausible changes to the landscape, they are not realistic scenarios in the sense that we are only evaluating one driver of change at a time. The Delta's landscape is much more likely to evolve due to a combination of these drivers and others not considered here.

The goals for this phase include:

* Compare alternative scenarios to identify and summarize the direction and magnitude of the changes to multiple metrics of interest, and to understand synergies and trade-offs among multiple goals

* Demonstrate proof-of-concept and encouraging the future use and further development of this framework for understanding and communicating co-benefits and trade-offs

Our baseline landscape is based on the [Delta Vegetation and Land Use Update 2016](https://map.dfg.ca.gov/metadata/ds2855.html), which includes detailed crop data from 2014. We further modified this baseline landscape to reflect changes in annual crop distributions and continued expansion of perennial crops based on [Statewide Crop Mapping Data](https://data.cnra.ca.gov/dataset/statewide-crop-mapping) through 2018. From this baseline layer, we have drafted three future scenarios:

1) A restoration scenario, in which the total area of riparian vegetation and non-tidal, seasonal wetlands are expanded to meet the [performance measures targets](https://deltacouncil.ca.gov/pdf/delta-plan/2020-04-15-draft-ch-04-pm-4-16.pdf) for the total area of each of these land covers by 2050, as identified in the proposed amendment to the Delta Plan. This scenario includes several of the restoration projects already planned or in-progress, as in [EcoAtlas](https://ecoatlas.org/regions/ecoregion/bay-delta).

2) A perennial crops expansion scenario, in which historical regional trends of conversion rates continue through the year 2050, with no restoration or loss of existing wetland and riparian area. This scenario is adapted from projections developed by [Wilson et al. (2021)](https://www.sciencebase.gov/catalog/item/6042c93fd34eb1203119dcaa).

3) A flood risk scenario, reflecting preparation for increasing flood risk due to sea level rise, based on projections of annual flood risk by 2050 developed for the [Delta Adapts](https://deltacouncil.ca.gov/delta-plan/climate-change) climate change vulnerability analyses and [supporting maps](https://deltascience.shinyapps.io/delta_flood_map/). Under this scenario, there are no changes to existing levees (no failures and no improvements), but areas with high (2-10%) and very high (>10%) annual risk of flooding are converted to managed wetlands as they become unsuitable for agriculture, and areas with a medium (1-2%) annual projected risk of flooding are converted to annual crops as they become unsuitable for perennial crops.

Explore the draft scenarios, in comparison to the baseline landscape, here:
<center>
<iframe src="map_widget.html" style="border: none;" width = 100%; height = 550px;></iframe>
</center>

### For more information

Please visit our [project overview](index.html), or contact [Dr. Kristen Dybala, Principal Ecologist, Point Blue Conservation Science](mailto:kdybala@pointblue.org).
