---
title: "Delta Scenarios"
output:
  html_document:
    theme: NULL
    css: delta_scenarios.css
---
As part of Point Blue's research examining multiple benefits in the Delta (see [project overview](index.html)), we have developed scenarios for the Delta's landscape in 2050. These are purely speculative scenarios chosen to represent distinct major drivers of landscape change, allowing us to estimate the direction and magnitude of the effects each scenario would have on multiple metrics of interest in the Delta. Aside from the planned restoration projects incorporated into the restoration scenario, these scenarios do not represent actual plans or recommendations, and while they are meant to represent reasonably plausible changes to the landscape, they are not realistic scenarios in the sense that we are only evaluating one driver of change at a time. The Delta's landscape is much more likely to evolve due to a combination of these drivers and others not yet considered here.

The goals for this phase include:

* Compare alternative scenarios to identify and summarize the direction and magnitude of the changes to multiple metrics of interest, and to understand synergies and trade-offs among multiple goals

* Demonstrate proof-of-concept and encouraging the future use and further development of this framework for understanding and communicating co-benefits and trade-offs

Our baseline landscape is based on the [Delta Vegetation and Land Use Update 2016](https://map.dfg.ca.gov/metadata/ds2855.html), which includes detailed crop data from 2014. We further modified this baseline landscape to reflect changes in annual crop distributions and continued expansion of perennial crops based on [Statewide Crop Mapping Data](https://data.cnra.ca.gov/dataset/statewide-crop-mapping) through 2018. From this baseline layer, we have developed two future scenarios:

1) A restoration scenario, in which the total area of riparian vegetation and non-tidal, seasonal wetlands are expanded to meet the [performance measures targets](https://deltacouncil.ca.gov/pdf/delta-plan/2020-04-15-draft-ch-04-pm-4-16.pdf) for the total area of each of these land covers by 2050, as identified in the proposed amendment to the Delta Plan. This scenario includes several of the restoration projects already planned or in-progress, as in [EcoAtlas](https://ecoatlas.org/regions/ecoregion/bay-delta).

2) A perennial crops expansion scenario, in which recent rates of conversion from annual crops to perennial crops continue through the year 2050, with no restoration effort. This scenario is adapted from projections developed by [Wilson et al. (2021)](https://www.sciencebase.gov/catalog/item/6042c93fd34eb1203119dcaa).

Explore the scenarios here: [[View fullscreen](widget/scenario_map.html)]  

<center>
<iframe src="widget/scenario_map.html" style="border: none;" width = 80%; height = 550px; data-external="1"></iframe>
</center>

### For more information

Please visit our [project overview](index.html), or contact [Dr. Kristen Dybala](mailto:kdybala@pointblue.org), Principal Ecologist, Point Blue Conservation Science.
