---
title: "Delta Scenarios"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Trade-offs and Co-benefits of Landscape Change Scenarios on Bird Communities and Ecosystem Services in the Sacramento-San Joaquin River Delta

### **Delta Water Quality and Ecosystem Restoration Program Grant Agreement Number – Q1996022**


### Project overview

Achieving the long-term vision of a resilient Sacramento-San Joaquin River Delta (Delta) 
ecosystem requires meeting multiple goals simultaneously, including self-sustaining wildlife populations and thriving communities of people, in an evolving landscape. To help meet this challenge, Point Blue Conservation Science is leading research to examine the effects of future landscape change in the Delta on bird populations and on the ecosystem services that benefit people in the Delta. This project will build on our partnerships in the Delta and broader Central Valley, and on our expertise in multiple-benefit conservation and avian ecology in 
agricultural landscapes to address two science needs: 

1) Identifying high priority areas for bird conservation in the Delta. We will capitalize on data recently collected in the Delta and surrounding areas of the Central Valley to model the spatial distribution and abundance of riparian landbirds, shorebirds, waterfowl, and other waterbirds. This analysis will allow us to project changes in these distributions under future landscape change, as well as identify areas within the Delta that are the highest priority to maintain for bird conservation.  

2) Developing a science-based framework for evaluating co-benefits and trade-offs among multiple goals. We will work with partners to identify important scenarios of future landscape change in the Delta, such as planned large-scale restoration and sea level rise. We will use these scenarios to evaluate the net effects of these landscape changes on bird populations and a selection of metrics representing different ecosystem services to people, such as air quality, water quality, or economic viability. This analysis will allow us to identify co-benefits and trade-offs under each of these scenarios, as well as develop a more generalized, open-source methodology for evaluating these co-benefits and trade-offs as these scenarios evolve and the landscape changes. 


### Objectives & Current status

The specific objectives of this Project are to: 

1. Synthesize scientific information on indicators of ecosystem services associated with land cover types that occur in the Delta. [Science synthesis report](http://www.prbo.org/refs/files/12650_PetersonCA2020.pdf) 

2. Model the distributions of waterbirds and riparian landbirds in the Delta, and identify high priority bird conservation areas in the Delta. [Summary report](http://www.prbo.org/refs/files/12713_DybalaKE2021.pdf)

3. Evaluate the net impact of scenarios of landscape change on bird populations and 
ecosystem services [**In progress**]

4. Develop a flexible, science-based framework for assessing the trade-offs and co-benefits 
of landscape changes [**In progress**]

5. Engage with partners to demonstrate the need to consider trade-offs and co-benefits in making land use decisions and provide training in how to use our science-based framework.

6. Disseminate results to the broader scientific community through scientific manuscripts and conference presentations.

Scenarios of landscape change under development for analysis of the net effects of these changes on birds and select ecosystem service metrics. 


### Work currently in progress (updated July 2021)

We are currently in the process of drafting and seeking input on spatially-explicit scenarios of future landscape change in the Delta to be evaluated under this project. We will apply our synthesis of ecosystem services and our distribution models of waterbirds and riparian land birds to each of these scenarios and to a baseline representation of the Delta's current landscape, to estimate the net effects of each scenario on ecosystem services and bird distributions and identify synergies and trade-offs among them.

Our baseline landscape is based on the [Delta Vegetation and Land Use Update 2016](https://map.dfg.ca.gov/metadata/ds2855.html), which includes detailed crop data from 2014. We further modified this baseline landscape to reflect changes in annual crop distributions and continued expansion of perennial crops based on [Statewide Crop Mapping Data](https://data.cnra.ca.gov/dataset/statewide-crop-mapping) from 2016 and 2018. From this baseline layer, we have drafted two future scenarios: 

1) A restoration scenario, in which the total area of riparian vegetation and non-tidal, seasonal wetlands are expanded to meet the [performance measures targets](https://deltacouncil.ca.gov/pdf/delta-plan/2020-04-15-draft-ch-04-pm-4-16.pdf) for the total area of each of these land covers by 2050, as identified in the proposed amendment to the Delta Plan, and

2) A scenario of continued expansion of perennial crops and urban development with no restoration, adapted from projections for the year 2100 under the "Bad Business As Usual" scenario developed by [Wilson et al. (2021)](https://www.sciencebase.gov/catalog/item/6042c93fd34eb1203119dcaa), which is in turn based on historical regional trends of land conversion probabilities in the Central Valley.

Explore the draft scenarios, in comparison to the baseline landscape, here:

[Initial draft scenarios](draft_scenarios.html)

